minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
allowBuilds:
  "@parcel/watcher": false
  esbuild: true
  sharp: false
  unrs-resolver: false
trustPolicyExclude:
  - "eslint-import-resolver-typescript@3.10.1"
  - "semver@6.3.1"
