/**
 * Generated by orval 🍺
 * Do not edit manually.
 * BookingService API (Sap-atitos)
 * Backend API responsible for ticket purchasing, idempotency handling, and issuance (MVP-02).
 * OpenAPI spec version: v1-commit-cf0898eb792920a40079504d353f4bcc987cf0fa
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface PurchaseTicketCommand {
  eventId?: string;
  ticketId?: string;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  idempotencyKey?: string;
}

export const getTestError = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/test/error`,options
    );
  }
export const getGetTestErrorUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/test/error`,
    baseURL: '',


  });
}

export const get = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/`,options
    );
  }
export const getGetUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/`,
    baseURL: '',


  });
}

export const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/health`,options
    );
  }
export const getGetHealthUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/health`,
    baseURL: '',


  });
}

export const postEventsEventIdTickets = (
    eventId: string,
    purchaseTicketCommand: PurchaseTicketCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/events/${eventId}/tickets`,
      purchaseTicketCommand,options
    );
  }
export const getPostEventsEventIdTicketsUrl = (eventId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/events/${eventId}/tickets`,
    baseURL: '',


  });
}

export type GetTestErrorResult = AxiosResponse<void>
export type GetResult = AxiosResponse<void>
export type GetHealthResult = AxiosResponse<void>
export type PostEventsEventIdTicketsResult = AxiosResponse<void>
