/**
 * Generated by orval 🍺
 * Do not edit manually.
 * BookingService API (Sap-atitos)
 * Backend API responsible for ticket purchasing, idempotency handling, and issuance (MVP-02).
 * OpenAPI spec version: v1-commit-cf0898eb792920a40079504d353f4bcc987cf0fa
 */
import { bookingInstance } from '../app/lib/api-mutator';
export interface PurchaseTicketCommand {
  eventId?: string;
  ticketId?: string;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  idempotencyKey?: string;
}

export interface TicketResponse {
  ticketId: string;
  eventId: string;
  seatNumber: string;
  fullName: string;
  email: string;
  ticketCode: string;
  /** @nullable */
  purchasedAtUtc?: string | null;
}

export type PostEventsEventIdTicketsHeaders = {
'X-Idempotency-Key'?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTestError = (

 options?: SecondParameter<typeof bookingInstance<void>>,) => {
      return bookingInstance<void>(
      {url: `/test/error`, method: 'GET'
    },
      options);
    }

export const get = (

 options?: SecondParameter<typeof bookingInstance<void>>,) => {
      return bookingInstance<void>(
      {url: `/`, method: 'GET'
    },
      options);
    }

export const getHealth = (

 options?: SecondParameter<typeof bookingInstance<void>>,) => {
      return bookingInstance<void>(
      {url: `/health`, method: 'GET'
    },
      options);
    }

export const postEventsEventIdTickets = (
    eventId: string,
    purchaseTicketCommand: PurchaseTicketCommand,
    headers?: PostEventsEventIdTicketsHeaders,
 options?: SecondParameter<typeof bookingInstance<TicketResponse>>,) => {
      return bookingInstance<TicketResponse>(
      {url: `/events/${eventId}/tickets`, method: 'POST',
      headers: {'Content-Type': 'application/json', ...headers},
      data: purchaseTicketCommand
    },
      options);
    }

export type GetTestErrorResult = NonNullable<Awaited<ReturnType<typeof getTestError>>>
export type GetResult = NonNullable<Awaited<ReturnType<typeof get>>>
export type GetHealthResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type PostEventsEventIdTicketsResult = NonNullable<Awaited<ReturnType<typeof postEventsEventIdTickets>>>
