/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DSaster-Search
 * OpenAPI spec version: 0.0.1
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface EventPreview {
  /** Identifier the event was registered with */
  id: string;
  /** Event name */
  name: string;
  /** Performing artist */
  artist: string;
  /** Date and time of the event, in ISO 8601 */
  date: string;
  /** Name of the venue hosting the event */
  venueName: string;
}

export interface RegisterVenueRequest {
  name: string;
  location: string;
}

export interface RegisterEventRequest {
  name: string;
  artist: string;
  date: string;
  venue: RegisterVenueRequest;
}

export interface Venue {
  name: string;
  location: string;
}

export interface Event {
  id: string;
  name: string;
  artist: string;
  date: string;
  venue: Venue;
}

export type EventsControllerFindParams = {
/**
 * Text to look for in the event name. The match is case-insensitive, ignores leading and trailing spaces, and succeeds when the event name contains the text
 */
name: string;
};

/**
 * Returns a preview of every registered event whose name contains the given text, in registration order.
 * @summary Search registered events by name
 */
export const eventsControllerFind = (
    params: EventsControllerFindParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EventPreview[]>> => {
    return axios.get(
      `/events`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getEventsControllerFindUrl = (params: EventsControllerFindParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/events`,
    baseURL: '',
    params,

  });
}

/**
 * @summary Register an event so it appears in search results
 */
export const eventsControllerRegister = (
    eventId: string,
    registerEventRequest: RegisterEventRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Event>> => {
    return axios.post(
      `/events/${eventId}`,
      registerEventRequest,options
    );
  }
export const getEventsControllerRegisterUrl = (eventId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/events/${eventId}`,
    baseURL: '',


  });
}

/**
 * @summary Get event details by ID
 */
export const eventsControllerGetDetails = (
    eventId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Event>> => {
    return axios.get(
      `/events/${eventId}`,options
    );
  }
export const getEventsControllerGetDetailsUrl = (eventId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/events/${eventId}`,
    baseURL: '',


  });
}

export type EventsControllerFindResult = AxiosResponse<EventPreview[]>
export type EventsControllerRegisterResult = AxiosResponse<Event>
export type EventsControllerGetDetailsResult = AxiosResponse<Event>
