/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DSaster-Search
 * OpenAPI spec version: 0.0.1
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Venue {
  name: string;
  location: string;
}

export interface Event {
  id: string;
  name: string;
  artist: string;
  date: string;
  venue: Venue;
}

export interface RegisterVenueRequest {
  name: string;
  location: string;
}

export interface RegisterEventRequest {
  name: string;
  artist: string;
  date: string;
  venue: RegisterVenueRequest;
}

export type EventsControllerFindParams = {
name: string;
};

export const eventsControllerFind = (
    params: EventsControllerFindParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Event[]>> => {
    return axios.get(
      `/events`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getEventsControllerFindUrl = (params: EventsControllerFindParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/events`,
    baseURL: '',
    params,

  });
}

/**
 * @summary Register an event so it appears in search results
 */
export const eventsControllerRegister = (
    eventId: string,
    registerEventRequest: RegisterEventRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Event>> => {
    return axios.post(
      `/events/${eventId}`,
      registerEventRequest,options
    );
  }
export const getEventsControllerRegisterUrl = (eventId: string,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/events/${eventId}`,
    baseURL: '',


  });
}

export type EventsControllerFindResult = AxiosResponse<Event[]>
export type EventsControllerRegisterResult = AxiosResponse<Event>
