/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DSaster-Search
 * OpenAPI spec version: 1.0.0
 */
import { searchInstance } from '../app/lib/api-mutator';
export interface EventPreview {
  /** Identifier the event was registered with */
  id: string;
  /** Event name */
  name: string;
  /** Performing artist */
  artist: string;
  /** Date and time of the event, in ISO 8601 */
  date: string;
  /** Name of the venue hosting the event */
  venueName: string;
}

export interface RegisterVenueRequest {
  name: string;
  location: string;
}

export interface RegisterEventRequest {
  name: string;
  artist: string;
  date: string;
  venue: RegisterVenueRequest;
}

export interface Venue {
  name: string;
  location: string;
}

export interface Event {
  id: string;
  name: string;
  artist: string;
  date: string;
  venue: Venue;
}

export type EventsControllerFindParams = {
/**
 * Text to look for in the event name. The match is case-insensitive, ignores leading and trailing spaces, and succeeds when the event name contains the text
 */
name: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Returns a preview of every registered event whose name contains the given text, in registration order.
 * @summary Search registered events by name
 */
export const eventsControllerFind = (
    params: EventsControllerFindParams,
 options?: SecondParameter<typeof searchInstance<EventPreview[]>>,) => {
      return searchInstance<EventPreview[]>(
      {url: `/events`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Register an event so it appears in search results
 */
export const eventsControllerRegister = (
    eventId: string,
    registerEventRequest: RegisterEventRequest,
 options?: SecondParameter<typeof searchInstance<Event>>,) => {
      return searchInstance<Event>(
      {url: `/events/${eventId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerEventRequest
    },
      options);
    }

/**
 * @summary Get event details by ID
 */
export const eventsControllerGetDetails = (
    eventId: string,
 options?: SecondParameter<typeof searchInstance<Event>>,) => {
      return searchInstance<Event>(
      {url: `/events/${eventId}`, method: 'GET'
    },
      options);
    }

export type EventsControllerFindResult = NonNullable<Awaited<ReturnType<typeof eventsControllerFind>>>
export type EventsControllerRegisterResult = NonNullable<Awaited<ReturnType<typeof eventsControllerRegister>>>
export type EventsControllerGetDetailsResult = NonNullable<Awaited<ReturnType<typeof eventsControllerGetDetails>>>
